export const ProductCategories = [
    { subCategory: "coffee", baseCategory: "pantry" },
    { subCategory: "beverage", baseCategory: "pantry" },
    { subCategory: "drink", baseCategory: "pantry" },
    { subCategory: "food", baseCategory: "pantry" },
    { subCategory: "countrybean", baseCategory: "pantry" },
    { subCategory: "soup", baseCategory: "pantry" },
    { subCategory: "knorr", baseCategory: "pantry" },
    { subCategory: "biscuit", baseCategory: "pantry" },
    { subCategory: "wafers", baseCategory: "pantry" },
    { subCategory: "ritebite", baseCategory: "pantry" },
    { subCategory: "parleg", baseCategory: "pantry" },
    { subCategory: "mobiles", baseCategory: "electronics" },
    { subCategory: "accessories", baseCategory: "electronics" },
    { subCategory: "earphones", baseCategory: "electronics" },
    { subCategory: "airdopes", baseCategory: "electronics" },
    { subCategory: "peripherals", baseCategory: "electronics" },
    { subCategory: "boat", baseCategory: "electronics" },
    { subCategory: "computers", baseCategory: "electronics" },
    { subCategory: "keyboard", baseCategory: "electronics" },
    { subCategory: "mouse", baseCategory: "electronics" },
    { subCategory: "gaming", baseCategory: "electronics" },
    { subCategory: "shirt", baseCategory: "clothing" },
    { subCategory: "wearables", baseCategory: "clothing" },
    { subCategory: "cotton", baseCategory: "clothing" },
    { subCategory: "dennis", baseCategory: "clothing" },
];